name: C++ CMake Conan Test Package

on:
  workflow_call:
    inputs:
      install-juce-dependencies:
        type: boolean
        default: false

jobs:
  package:
    env:
      CONAN_HOME: ${{ github.workspace }}/build/release/.conan2
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup
        uses: tnt-coders/ci-workflows/.github/actions/cpp-cmake-conan-setup@master
        with:
          install-juce-dependencies: ${{ inputs.install-juce-dependencies }}

      - name: Download Conan host profile
        uses: actions/download-artifact@v4
        with:
          name: conan-profile-${{ runner.os }}

      - name: Detect default profile
        run: conan profile detect

      - name: Create package
        run: conan create . --version=test --build=missing --profile:host=./conan_host_profile
